api = 2
core = 7.34

; Modules ========================================================
projects[backup_migrate][version] = 2.8
projects[backup_migrate][subdir] = contrib
projects[ctools][version] = 1.6
projects[ctools][subdir] = contrib
projects[date][version] = 2.8
projects[date][subdir] = contrib
projects[entity][version] = 1.5
projects[entity][subdir] = contrib
projects[imce][version] = 1.9
projects[imce][subdir] = contrib
projects[imce_wysiwyg][version] = 1.0
projects[imce_wysiwyg][subdir] = contrib
projects[jquery_update][version] = 2.5
projects[jquery_update][subdir] = contrib
projects[libraries][version] = 2.2
projects[libraries][subdir] = contrib
projects[link][version] = 1.3
projects[link][subdir] = contrib
projects[menu_block][version] = 2.5
projects[menu_block][subdir] = contrib
projects[menu_position][version] = 1.1
projects[menu_position][subdir] = contrib
projects[nodequeue][version] = 2.0-beta1
projects[nodequeue][subdir] = contrib
projects[pathauto][version] = 1.2
projects[pathauto][subdir] = contrib
projects[references][version] = 2.1
projects[references][subdir] = contrib
projects[token][version] = 1.5
projects[token][subdir] = contrib
projects[views][version] = 3.10
projects[views][subdir] = contrib
projects[wysiwyg][version] = 2.2
projects[wysiwyg][subdir] = contrib

; Themes =========================================================
projects[halftheme][type] = theme
projects[halftheme][download][type] = git
projects[halftheme][download][url] = "git://github.com/ericojeda/halftheme.git"
projects[halftheme][download][branch] = master

; Libraries ======================================================
libraries[ckeditor][type] = library
libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url] = "https://github.com/ericojeda/ckeditor.git"